services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: lovelystay
      POSTGRES_PASSWORD: lovelystay
    networks:
      - lovelystay
  
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

networks:
  lovelystay:
    driver: bridge

